#!/bin/bash
brew install libomp > /dev/null
brew install armadillo > /dev/null
clang++ -std=c++11 -Xpreprocessor -fopenmp -larmadillo -march=native -lomp scripts/hypercube.cpp -o hypercube
./hypercube $@

# For debugging:
# valgrind --leak-check=full ./hypercube
